version: 2.1

jobs:
  test:
    macos:
      xcode: 13.4
    steps:
#      - checkout
#      - run: sw_vers # OS Version 2022/6/3現在 12.3.1
      - run: xcodebuild -version

workflows:
  job-workflow:
    jobs:
      - test
