version: 2.1

jobs:
  test:
    macos:
      xcode: 13.4
    steps:
#      - checkout
#      - run: sw_vers # OS Version 2022/6/3現在 12.3.1
#      - run: xcodebuild -version # Xcode Version 2022/6/3現在 13.4

      - run: curl https://go.dev/dl/go1.18.3.darwin-arm64.pkg -o darwin-arm64.pkg 
      - run: ls -la

#      - run: go version

workflows:
  job-workflow:
    jobs:
      - test
