version: 2.1

jobs:
  test:
    macos:
      xcode: 13.4
    steps:
#      - checkout
#      - run: sw_vers # OS Version 2022/6/3現在 12.3.1
#      - run: xcodebuild -version # Xcode Version 2022/6/3現在 13.4

#      - run: curl https://go.dev/dl/go1.18.3.darwin-arm64.pkg -o darwin-arm64.pkg
#      - run: ls -la
#      - run: sudo installer -pkg ./darwin-arm64.pkg -target /

# Go言語のインストール
#      - run: brew install go
#      - run: brew install go@1.17
#      - run: export PATH="/usr/local/opt/go@1.17/bin:$PATH"
#      - run: go version # GO 2022/6/6現在 1.18.3 darwin/amd64
      - run: mkdir $HOME/go
      - run: ls -la $HOME
      - run: echo 'export GOPATH=$HOME/go' >> $BASH_ENV
      - run: export

workflows:
  job-workflow:
    jobs:
      - test
