version: 2.1

jobs:
  test:
    macos:
      xcode: 13.4
    steps:
#      - run: sw_vers # OS Version 2022/6/3現在 12.3.1
#      - run: xcodebuild -version # Xcode Version 2022/6/3現在 13.4

# opensslのインストール
      - run: curl https://www.openssl.org/source/old/1.1.1/openssl-1.1.1n.tar.gz -o $HOME/Downloads/openssl-1.1.1n.tar.gz
      - run: sudo mkdir /usr/local/src
      - run: cd /usr/local/src
      - run: sudo cp $HOME/Downloads/openssl-1.1.1n.tar.gz .
      - run: sudo tar xzvf openssl-1.1.1n.tar.gz
      - run: ls -la

# Go言語のインストール
##      - run: curl https://go.dev/dl/go1.18.3.darwin-arm64.pkg -o darwin-arm64.pkg
##      - run: ls -la
##      - run: sudo installer -pkg ./darwin-arm64.pkg -target /

#      - run:
#         name: "go install"
#         command: brew install go
##      - run: brew install go@1.17
##      - run: export PATH="/usr/local/opt/go@1.17/bin:$PATH"
##      - run: go version # GO 2022/6/6現在 1.18.3 darwin/amd64

#      - run: mkdir $HOME/go
#      - run: echo 'export GOPATH=$HOME/go' >> $BASH_ENV
##      - run: export

# ソースコードの取得
#      - checkout

workflows:
  job-workflow:
    jobs:
      - test
